[build]
  command = "ng build"
  publish = "dist/biblia/browser"

# Redirigir a HTTPS solo si no es localhost (desarrollo local)
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  conditions = { Country = ["!US"], Role = ["!admin"] }
  force = true
